# Web-scraping Assignment-4

## Question-1

In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

In [2]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [3]:
driver = webdriver.Chrome(PATH)
driver.get("https://en.wikipedia.org/wiki/List_of most-viewed_YouTube_videos")

time.sleep(2) # Going to link

In [4]:
ranks = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[1]')
vid_names = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[2]')
artists = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[3]')
dates = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[5]')
views = driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr/td[4]') # Finding required elements

In [5]:
rank = []
name = []
artist = []
date = []
view = [] # Empty list for appending

In [6]:
def append(path,li): # This is a function I have created which will be used throughout the assignment to not repeat same piece of code again and again
    for i in path:
        li.append(i.text)   # This function basically iterates the text from each element from seleenium driver and appends it to the list provided.

In [7]:
append(vid_names,name)
append(ranks,rank)
append(artists,artist)
append(dates,date)
append(views,view) # Using the append function

In [8]:
wiki_df = pd.DataFrame({})
wiki_df['Rank'] = rank
wiki_df['Name'] = name
wiki_df['Artist'] = artist
wiki_df['Upload date'] = date
wiki_df['Views (in billions)'] = view # Assigning dataframe and filling it

In [9]:
wiki_df

,Rank,Name,Artist,Upload date,Views (in billions)
0,1.,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",9.20
1,2.,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.50
2,3.,"""Johny Johny Yes Papa""[25]",LooLoo Kids,"October 8, 2016",5.65
3,4.,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",5.43
4,5.,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.23
5,6.,"""Bath Song""[30]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.47
6,7.,"""Learning Colors – Colorful Eggs on a Farm""[31]",Miroshka TV,"February 27, 2018",4.45
7,8.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.45
8,9.,"""Uptown Funk""[33]",Mark Ronson,"November 19, 2014",4.27
9,10.,"""Gangnam Style""[34]",Psy,"July 15, 2012",4.16
10,11.,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",4.10
11,12.,"""Dame Tu Cosita""[37]",El Chombo,"April 5, 2018",3.54
12,13.,"""Sugar""[38]",Maroon 5,"January 14, 2015",3.54
13,14.,"""Sorry""[39]",Justin Bieber,"October 22, 2015",3.46
14,15.,"""Roar""[40]",Katy Perry,"September 5, 2013",3.41
15,16.,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.37
16,17.,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.31
17,18.,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.23
18,19.,"""Dark Horse""[44]",Katy Perry,"February 20, 2014",3.13
19,20.,"""Faded""[45]",Alan Walker,"December 3, 2015",3.12
20,21.,"""Girls Like You""[46]",Maroon 5,"May 31, 2018",3.10
21,22.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.09
22,23.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.08
23,24.,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.08
24,25.,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.06
25,26.,"""Mi Gente""[51]",J Balvin,"June 29, 2017",2.96
26,27.,"""Axel F""[52]",Crazy Frog,"June 16, 2009",2.95
27,28.,"""Perfect""[53]",Ed Sheeran,"November 9, 2017",2.93
28,29.,"""Waka Waka (This Time for Africa)""[54]",Shakira,"June 4, 2010",2.92
29,30.,"""Hello""[55]",Adele,"October 22, 2015",2.87

In [10]:
time.sleep(3)
driver.quit() # Quit

## Question-2

In [11]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

In [12]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [13]:
driver = webdriver.Chrome(PATH)
driver.get("https://www.bcci.tv")

time.sleep(4) # Reaching the target link

In [14]:
link_fix = driver.find_element_by_xpath('/html/body/footer/div/nav/ul/li[2]/ul/li[1]/a') # We need to click further

In [15]:
link_fix.click() # Click
time.sleep(3)

In [16]:
dates = driver.find_elements_by_xpath("//div[@class='fixture__full-date']/span") # Finding required elements
months = driver.find_elements_by_xpath("//span[@class='fixture__month']")
times = driver.find_elements_by_xpath("//span[@class='fixture__time']") 
place = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
series = driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']") 
match_title = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/strong")

In [17]:
date = [] # Defining empty lists
month = []
time_li = []
place_li = []
series_li = []
title = []

In [18]:
append(dates,date) # Using append function
append(months,month)
append(times,time_li)
append(place,place_li)
append(series,series_li)
append(match_title,title)

In [19]:
bcci = pd.DataFrame({}) # Creating data frame and filling it
bcci['Match Title'] = title
bcci['Series'] = series_li
bcci['Place'] = place_li
bcci['Date (day)'] = date
bcci['Date (month)'] = month
bcci['Time'] = time_li

In [20]:
bcci # View data frame

,Match Title,Series,Place,Date (day),Date (month),Time
0,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02,SEPTEMBER,15:30 IST
1,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",10,SEPTEMBER,15:30 IST
2,Match 16,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",24,OCTOBER,19:30 IST
3,Match 28,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",31,OCTOBER,19:30 IST
4,Match 33,2021 ICC MEN'S T20 WORLD CUP,"Sheikh Zayed Cricket Stadium, Abu Dhabi",03,NOVEMBER,19:30 IST
5,Match 37,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",05,NOVEMBER,19:30 IST
6,Match 42,2021 ICC MEN'S T20 WORLD CUP,"Dubai International Cricket Stadium, Dubai",08,NOVEMBER,19:30 IST

In [21]:
time.sleep(3)
driver.quit() # Quit

## Question-3

In [22]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

In [23]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [24]:
driver = webdriver.Chrome(PATH)
driver.get("https://www.guru99.com/")

time.sleep(4) # Going to target link

In [25]:
page_1 = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a[1]').click()
time.sleep(3) # We need to go further to a link

In [26]:
page_2 = driver.find_element_by_xpath('//*[@id="post-193"]/div/div/table[5]/tbody/tr[34]/td[1]/a/strong').click()
time.sleep(3) # Going further to final link

In [27]:
all_ = driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td") # Finding required elements

In [28]:
all_li = [] # Empty list

In [29]:
append(all_,all_li) # Using the append fucntion

In [30]:
name = [] # Empty list
desc = []

In [31]:
for i in range(0,len(all_li),2): # truncating the initial list to and slicing data under correct list
    name.append(all_li[i])

for i in range(1,len(all_li),2):
    desc.append(all_li[i])

In [32]:
print(len(name),len(desc))

41 41

In [33]:
sel_df = pd.DataFrame({}) # Creatign and assigning values to Data frame
sel_df['Name'] = name
sel_df['Description'] = desc

In [34]:
sel_df # View

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [35]:
time.sleep(3)
driver.quit() # Quit

## Question-4

In [36]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

In [37]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [38]:
driver = webdriver.Chrome(PATH)
driver.get("http://statisticstimes.com/")

time.sleep(4) # Going to target link

In [39]:
time.sleep(2)
link_eco = driver.find_elements_by_xpath("//button[@class='dropbtn']")

In [40]:
link_eco[1].click()
time.sleep(2) # Navigating forward

In [41]:
link_eco_down = driver.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]').click()
time.sleep(3) # Navigating forward

In [42]:
link_gdp_state = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(4) # Navigating to final link

In [43]:
all_text = driver.find_elements_by_xpath("//tr[@role='row']/td") # Finding required elements

In [44]:
all_text = all_text[:264] # truncating list to remove excess data

In [45]:
rank = []
state = []
GSDP_19 = []
GSDP_18 = []
share = []
GDP = []

In [46]:
for i in range(0,len(all_text),8): # truncating the initial list to and slicing data under correct list
    rank.append(all_text[i].get_attribute('textContent')) 

for i in range(1,len(all_text),8):
    state.append(all_text[i].get_attribute('textContent'))
    
for i in range(2,len(all_text),8):
    GSDP_19.append(all_text[i].get_attribute('textContent'))

for i in range(3,len(all_text),8):
    GSDP_18.append(all_text[i].get_attribute('textContent'))
    
for i in range(4,len(all_text),8):
    share.append(all_text[i].get_attribute('textContent'))

for i in range(5,len(all_text),8):
    GDP.append(all_text[i].get_attribute('textContent'))

In [47]:
GDP_df = pd.DataFrame({}) # Creating dataframe, and filling values 
GDP_df['Rank'] = rank
GDP_df['State'] = state
GDP_df['GSDP (19-20)'] = GSDP_19
GDP_df['GSDP (18-20)'] = GSDP_18
GDP_df['Share (18-19)'] = share
GDP_df['GDP ($ billion)'] = GDP

In [48]:
GDP_df # View

,Rank,State,GSDP (19-20),GSDP (18-20),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [49]:
time.sleep(3)
driver.quit() # Quit

## Question-5

In [50]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains

In [51]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [52]:
driver = webdriver.Chrome(PATH)
driver.get("https://github.com/trending")

time.sleep(3) # Going to target link

In [53]:
links = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a") # Finding required elements

In [54]:
urls = []

In [55]:
for i in links: # Getting URLs from the href attribute
    urls.append(i.get_attribute('href'))

In [56]:
titles = [] # Empty list
descriptions = []
cont_counts = []
langs = []

In [57]:
for link in urls: # Going to each link and finding the follow data
    driver.get(link)
    time.sleep(2)
    
    try:
        element = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.ID, "repository-container-header"))
        )
    except:
        driver.quit()
        
    try:
        desc = driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[1]/div/p')
        descriptions.append(desc.text) # Finding required elements
    except NoSuchElementException:
        descriptions.append('No description, website, or topics provided.')
        
    try:
        title = driver.find_element_by_xpath("//strong[@class='mr-2 flex-self-stretch']/a")
        titles.append(title.text) # Finding required elements
    except NoSuchElementException:
        titles.append('No title.')
        
    try:
        cont = driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[5]/div/h2/a/span')
        cont_counts.append(cont.text) # Finding required elements
    except NoSuchElementException:
        cont_counts.append('Solo contributor.')
        
    try:
        lang = driver.find_element_by_xpath("//a[@class='d-inline-flex flex-items-center flex-nowrap Link--secondary no-underline text-small mr-3']")
        langs.append(lang.get_attribute('textContent').replace('\n','')) # Finding required elements
    except NoSuchElementException:
        langs.append('Magic.')

In [58]:
git_df = pd.DataFrame({}) # Creating data frame, and filling it with values we have scraped.
git_df['Repository tile'] = titles
git_df['Repository description'] = descriptions
git_df['Contributors count'] = cont_counts
git_df['Language used'] = langs

In [59]:
git_df # View

,Repository tile,Repository description,Contributors count,Language used
0,nft-image-generator,"No description, website, or topics provided.",Solo contributor.,Jupyter Notebook 88.8% ...
1,server,"☁️ Nextcloud server, a safe home for all your ...",Solo contributor.,PHP 61.9%
2,The-Complete-FAANG-Preparation,This repository contains all the DSA (Data-Str...,48,Jupyter Notebook 55.2% ...
3,whoogle-search,"A self-hosted, ad-free, privacy-respecting met...",Solo contributor.,Python 54.0%
4,lite-xl,A lightweight text editor written in Lua,Solo contributor.,Lua 60.9%
5,qinglong,Python/JavaScript/Shell/Typescript 定时任务管理,Solo contributor.,TypeScript 71.8%
6,chia-blockchain,Chia blockchain python implementation (full no...,99,Python 99.1%
7,macos-virtualbox,"Push-button installer of macOS Catalina, Mojav...",Solo contributor.,Shell 100.0%
8,free-programming-books,📚 Freely available programming books,Solo contributor.,Magic.
9,binance-trading-bot-new-coins,This Binance trading bot detects new coins as ...,Solo contributor.,Python 100.0%
10,Docker_training_with_DockerMe,The tools and sample needed to learn the Docker,Solo contributor.,HTML 58.7%
11,discord.py,An API wrapper for Discord written in Python.,271,Python 100.0%
12,generative-art-node,Create generative art by using the canvas api ...,Solo contributor.,JavaScript 100.0%
13,RobustVideoMatting,"Robust Video Matting in PyTorch, TensorFlow, T...",Solo contributor.,Python 100.0%
14,iced,"A cross-platform GUI library for Rust, inspire...",93,Rust 99.6%
15,devops-exercises,"Linux, Jenkins, AWS, SRE, Prometheus, Docker, ...",51,Python 83.3%
16,joplin,Joplin - an open source note taking and to-do ...,401,TypeScript 53.1%
17,bsc,A Binance Smart Chain client based on the go-e...,134,Go 89.8%
18,Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",87,JavaScript 78.5%
19,MeiliSearch,"Powerful, fast, and an easy to use search engine",56,Rust 97.3%
20,engineering-blogs,A curated list of engineering blogs,Solo contributor.,Ruby 100.0%
21,DSA-Bootcamp-Java,"This repository consists of the code samples, ...",37,Java 98.8%
22,jina,Cloud-native neural search framework for 𝙖𝙣𝙮 k...,Solo contributor.,Python 96.9%
23,windows11,windows 11 in react 💻🌈⚡,Solo contributor.,CSS 91.4%
24,td,Cross-platform library for building Telegram c...,Solo contributor.,C++ 95.2%

In [60]:
time.sleep(3)
driver.quit() # Quit

## Question-6

In [61]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains

In [62]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [63]:
driver = webdriver.Chrome(PATH)
driver.get("https://www.billboard.com/")

time.sleep(3) # Going to target link

In [64]:
link_top = driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/nav/ul/li[5]/a') # Finding link for next page

In [65]:
link_top.click() # clicking said link
time.sleep(3)

In [66]:
name = driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[1]") # Finding required elements
author = driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[2]")
last_rank = driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
peak_rank = driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
weeks_on = driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")

In [67]:
names = [] # Empty lists
authors = []
last_ranks = []
peak_ranks = []
weeks_ons = []

In [68]:
append(name,names) # Using the append function
append(author,authors)
append(last_rank,last_ranks)
append(peak_rank,peak_ranks)
append(weeks_on,weeks_ons)

In [69]:
bill_df = pd.DataFrame({}) # Creating data frame, and filling it with values we have scraped.
bill_df['Song name'] = names
bill_df['Artist name'] = authors
bill_df['Last week rank'] = last_ranks
bill_df['Peak rank'] = peak_ranks
bill_df['Weeks on board'] = weeks_ons

In [70]:
bill_df # View

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Stay,The Kid LAROI & Justin Bieber,1,1,6
1,Bad Habits,Ed Sheeran,2,1,8
2,Industry Baby,Lil Nas X & Jack Harlow,3,3,4
3,Beggin',Maneskin,4,3,11
4,Good 4 U,Olivia Rodrigo,6,1,14
...,...,...,...,...,...
95,Queendom,Red Velvet,-,96,1
96,Dreams,Fleetwood Mac,89,10,47
97,Every Chance I Get,DJ Khaled Featuring Lil Baby & Lil Durk,90,27,16
98,Papercuts,Machine Gun Kelly,-,99,1
99,Positions,Ariana Grande,83,1,43

In [71]:
time.sleep(3)
driver.quit() # Quit

## Question-8

In [72]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains

In [73]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [74]:
driver = webdriver.Chrome(PATH)
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

time.sleep(3) # Going to target link

In [75]:
book_name = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]") # Finding required elements
auth_name = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
vol_sold = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
pub = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
genre = driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")

In [76]:
book_names = [] # Empty list
auth_names = []
vols_sold = []
pubs = []
genres = []

In [77]:
append(book_name,book_names) # Using the append function
append(auth_name,auth_names)
append(vol_sold,vols_sold)
append(pub,pubs)
append(genre,genres)

In [78]:
guard_df = pd.DataFrame({}) # Creating data frame, and filling it with values we have scraped.
guard_df['Book name'] = book_names
guard_df['Author name'] = auth_names
guard_df['Volumes sold'] = vols_sold
guard_df['Publisher'] = pubs
guard_df['Genre'] = genres

In [79]:
guard_df # view

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [80]:
time.sleep(3)
driver.quit() # Quit

## Question-9

In [81]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains

In [82]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [83]:
driver = webdriver.Chrome(PATH)
driver.get("https://www.imdb.com/list/ls095964455/")

time.sleep(3) # Going to target link

In [84]:
name = driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a") # Finding required elements
year = driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
genre = driver.find_elements_by_xpath("//span[@class='genre']")
run_time = driver.find_elements_by_xpath("//span[@class='runtime']")
rating = driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
vote = driver.find_elements_by_xpath("//span[@name='nv']")

In [85]:
names = [] # Empty lists
years = []
genres = []
run_times = []
ratings = []
votes = []

In [86]:
append(name,names) # Using the append fucntion
append(year,years)
append(genre,genres)
append(run_time,run_times)
append(rating,ratings)
append(vote,votes)

In [87]:
imdb_df = pd.DataFrame({}) # Creating data frame, and filling it with values we have scraped.
imdb_df['Name'] = names
imdb_df['Year span'] = years
imdb_df['Genre'] = genres
imdb_df['Run time'] = run_times
imdb_df['Ratings'] = ratings
imdb_df['Votes'] = votes

In [88]:
imdb_df # View

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,863,954"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"899,759"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"892,759"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"268,786"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,027"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,400"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,265"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"173,827"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,386"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"197,661"

In [89]:
time.sleep(3)
driver.quit() # Quit

## Question-10

In [90]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd # Importing the required libraries
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains

In [91]:
PATH = "C:\Program Files (x86)\chromedriver.exe" # Defining path

In [92]:
driver = webdriver.Chrome(PATH)
driver.get("https://archive.ics.uci.edu/")

time.sleep(3) # Going to target link

In [93]:
link = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td/span/b/a") # Finding xpath for required page

In [94]:
link.click() # Going to next page
time.sleep(2)

In [95]:
name = driver.find_elements_by_xpath('//tbody/tr/td/table/tbody/tr/td[2]/p/b/a') # Finding required elements
data_type = driver.find_elements_by_xpath('//tbody/tr/td[2]/p')
task = driver.find_elements_by_xpath('//tbody/tr/td[3]/p')
att_type = driver.find_elements_by_xpath('//tbody/tr/td[4]/p')
no_ins = driver.find_elements_by_xpath('//tbody/tr/td[5]/p')
no_att = driver.find_elements_by_xpath('//tbody/tr/td[6]/p')
year = driver.find_elements_by_xpath('//tbody/tr/td[7]/p')

In [96]:
data_type = data_type[2:] # Truncating lists as they have some unwanted values in start and/or at the end of the elements.
task = task[1:-1]
att_type = att_type[1:]
no_ins = no_ins[1:]
no_att = no_att[1:]
year = year[1:]

In [97]:
print(len(name),len(data_type),len(task),len(att_type),len(no_ins),len(no_att),len(year)) # Getting length of all elements

588 1176 588 588 588 588 588

In [98]:
names = [] # Empty lists
dts = []
tasks = []
types = []
ins = []
att = []
years = []

In [99]:
append(name,names) # Using the append function
append(task,tasks)
append(att_type,types)
append(no_ins,ins)
append(no_att,att)
append(year,years)
for i in range(1,len(data_type),2): # truncating the initial list to and slicing data under correct list
    dts.append(data_type[i].text)

In [100]:
uci_df = pd.DataFrame({}) # Creating data frame, and filling it with values we have scraped.
uci_df['Dataset name'] = names
uci_df['Data type'] = dts
uci_df['Task'] = tasks
uci_df['Attribute  type'] = types
uci_df['No. of instances'] = ins
uci_df['No. of attributes'] = att
uci_df['Year'] = years

In [101]:
uci_df # View

,Dataset name,Data type,Task,Attribute type,No. of instances,No. of attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

In [102]:
time.sleep(3)
driver.quit() # Quit

# End of assignment